### ISSUE TITLE
instalation problem on mailcoach 2

### ISSUE THREAD

**Issue by agus-ngorder** [leeovery/mailcoach-api#4]
Hi i got error when install this package

` Problem 1
    - Installation request for leeovery/mailcoach-api ^2.0 -> satisfiable by leeovery/mailcoach-api[v2].
    - Conclusion: remove laravel/framework v7.4.0
    - Conclusion: don't install laravel/framework v7.4.0
    - leeovery/mailcoach-api v2 requires illuminate/support ^6.0 -> satisfiable by laravel/framework[6.x-dev], illuminate/support[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.2, v6.18.3, v6.18.4, v6.18.5, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - Can only install one of: laravel/framework[6.x-dev, v7.4.0].
`

**Comment by timmoh** [comment]
See #6 
@leeovery could you merge

**Comment by leeovery** [comment]
Should be sorted now. Thanks for PR @timmoh
